Subo parte del Back de la tabla Producto
Daniel-GB0319/proyecto-ch39 pull request #112
Opened 2024-05-28 17:02 UTC by Monttze

2024-05-28 18:47 UTC, JPinaSuarez approved these changes

2024-05-28 18:51 UTC, Duarlo approved these changes

2024-05-28 19:26 UTC, Daniel-GB0319 requested changes
En controller y services del producto se esta pidiendo/trabajando el id de usuario como parámetro en varias funciones, sin embargo en la URL de la API no se pide dicha id (tal vez solo sea necesario el usuario al crear un producto porque se necesita registrar un vendedor) . Verificar que en model se haga bien la referencia a las columnas qué son llaves foráneas.

2024-05-28 21:53 UTC, Duarlo submitted a review, later dismissed

2024-05-29 02:52 UTC, Daniel-GB0319 approved these changes

2024-05-29 02:52 UTC, merged