Card Lino
Daniel-GB0319/proyecto-ch39 pull request #34
Opened 2024-05-04 03:04 UTC by Ino117

Agregué mi foto y presentación

2024-05-04 14:41 UTC, Duarlo reviewed
# Respuesta a PR 34
## Saludos
Respuesta: Rechazado
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/97e4106c-0074-472a-bdd9-678766c3cc0d)
Editaste sobre la carpeta de prueba jajaj *(no la hemos eliminado no se porque)* 
porfa pasa tus datos sobre la pagina de contacto **nosotros.html** apartir de la linea 274 inicia tu card.
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/0eb17694-0631-4952-b5dc-fb6c55e0c7be)

Tambien a la velocidad que estamos revisando los PR's  podrias eliminar la carpeta **CardELM** si no en la siguiente PR que suba ya la quito.

2024-05-04 15:18 UTC, JPinaSuarez approved these changes
Aprobado

2024-05-04 15:18 UTC, JPinaSuarez approved these changes
x2

2024-05-04 16:30 UTC, Monttze commented
Ademas de que la fotografía debe ser cuadrada para que no quede ovalada por fis ino

2024-05-04 19:00 UTC, Ino117 reviewed
Quedo pendiente cualquier revisión

![440387723_3566716630324749_7932903156088375591_n](https://github.com/Daniel-GB0319/proyecto-ch39/assets/163358417/cd1ffcd5-4b0e-46ab-98ff-907a32bcfa2f)

2024-05-04 19:12 UTC, Monttze submitted a review, later dismissed
Bien bien perfecto c:

2024-05-04 19:13 UTC, Duarlo requested changes
# Revisión a PR #34 
ya revise la imagen ya esta en un perfil cuadrado 💯
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/926c9f04-d3cf-4576-838a-b1564be2acfd)
y tambien ya esta en la parte de **nosotros.html** 💯
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/bb846ccb-784c-4dc2-a6b0-45489283153e)
Sin embargo no aparece tu imagen no se si sea solo yo , por lo que necesito que alguien más revise. lo probe con la siguiente direción `"../../public/assets/fotosIntegrantes/440733807_964235551753954_2002067955623461711_n (1) (1).jpg"` ahora si funciona.
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/6a79e8ad-7365-44c3-94ca-35def0ee8911)
pero necesito que alguien más confirme este problema, sin embargo excelente trabajo.

2024-05-04 19:15 UTC, Monttze commented
> # Revisión a PR #34
> ya revisa la imagen ya esta en un perfil cuadrado 💯 y tambien ya esta en la parte de **nosotros.html** 💯 Sin embargo no aparece tu imagen no se si sea solo yo , por lo que necesito que alguien más revise. lo probe con la siguiente dirección ahora si funciona. pero necesito que alguien más confirme este problema, sin embargo excelente trabajo. ![imagen](https://private-user-images.githubusercontent.com/130912792/327969546-926c9f04-d3cf-4576-838a-b1564be2acfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTAzMzYsIm5iZiI6MTcxNDg1MDAzNiwicGF0aCI6Ii8xMzA5MTI3OTIvMzI3OTY5NTQ2LTkyNmM5ZjA0LWQzY2YtNDU3Ni04MzhhLWIxNTY0YmUyYWNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxOTEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I1NWVkOGVlOGJhZDg4MmVjNjUxMmE3NzRjOTJiNGVlZjAyNjE1YTBkYjU3NjlhNTdlMjcwOWQ4ODdjOGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Sn5rFN4VN4hiZDL8QQek4kb3WdUjaXHDTJ-NDKiidyc)**** ![imagen](https://private-user-images.githubusercontent.com/130912792/327969522-bb846ccb-784c-4dc2-a6b0-45489283153e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTAzMzYsIm5iZiI6MTcxNDg1MDAzNiwicGF0aCI6Ii8xMzA5MTI3OTIvMzI3OTY5NTIyLWJiODQ2Y2NiLTc4NGMtNGRjMi1hNmIwLTQ1NDg5MjgzMTUzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxOTEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjY3YmFmYzBlMjY4NzVhZjk5ODE1YWI5YWE3NzNlMWRmODU5YzllNTczYmRjMWEyZDgyZWQwY2ExNTg5OTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L_O_jYt2re_VOknbTscqJ-l6zGEOSGLd5tvQS2joa88)`"../../public/assets/fotosIntegrantes/440733807_964235551753954_2002067955623461711_n (1) (1).jpg"` ![imagen](https://private-user-images.githubusercontent.com/130912792/327969918-6a79e8ad-7365-44c3-94ca-35def0ee8911.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4NTAzMzYsIm5iZiI6MTcxNDg1MDAzNiwicGF0aCI6Ii8xMzA5MTI3OTIvMzI3OTY5OTE4LTZhNzllOGFkLTczNjUtNDRjMy05NGNhLTM1ZGVmMGVlODkxMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxOTEzNTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZmI0OTVjYjYzMTY0NzdlNWI3NmIzYjRmOGJhMzg3ZDQ5ZTEyYzNjZmZiNDM2MDZhNjkzODgzY2IyY2Y5OWJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IZfcCldDngbLuWZk6oyY76BgMNIcTriAS-u9XSQf7ic)


Hay un problema con su rama :'(

2024-05-04 19:19 UTC, Duarlo commented
Hay un problema con su rama :'(

Es momento de llamar a @Daniel-GB0319  ya le dimos en la madre otra vez al github.
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/b9f3f19e-a084-4db8-ac83-938e35b20713)

2024-05-04 19:24 UTC, Monttze commented
@Daniel-GB0319 yo te elijo jajajajaja no inventes valio cheto

2024-05-04 20:25 UTC, Ino117 commented
jajajajaaja ya lo rompí

2024-05-04 21:56 UTC, Daniel-GB0319 commented
Apenas arreglé una rama ayer y no pasó ni un dia jaja

![here_we_go_again](https://github.com/Daniel-GB0319/proyecto-ch39/assets/83619266/d9e9b2ee-916d-4fa4-9bb6-1ef1e14af41d)

2024-05-05 03:37 UTC, JPinaSuarez approved these changes
Ya ahora si aprovado

2024-05-05 03:38 UTC, Monttze approved these changes
Ya quedo c:

2024-05-05 03:42 UTC, JPinaSuarez approved these changes
Ya quedo

2024-05-05 03:54 UTC, Daniel-GB0319 approved these changes
Aprobado, muy bien

2024-05-05 03:56 UTC, Duarlo requested changes
# Respuesta a PR #34 
todavia persiste el problema...
Anexo evidencia.

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/d1f29d66-68a3-4fa3-8f6e-65211d7bec9e)

---
**Veredicto: Rechazado**

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/8209a899-4c2d-49dd-83f5-b4f9ea708953)

2024-05-05 04:16 UTC, JPinaSuarez submitted a review, later dismissed

2024-05-05 05:25 UTC, Monttze approved these changes
Va pues ya quedo aparentemente jajajaja

2024-05-05 05:27 UTC, Duarlo approved these changes
# Revisión a PR #34 

**Descisión: aprobado**

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/4184d432-c01a-4648-b268-2efd12f94cb0)

---

adjunto evidencia:
![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/4828cf10-ab17-4d74-96a6-5f2834c42f71)

Ya puedes dormir tranquilo.

![image](https://github.com/Daniel-GB0319/proyecto-ch39/assets/130912792/bf862584-d5bc-4c8c-b688-b8b06a803e31)

2024-05-05 18:00 UTC, JPinaSuarez approved these changes
Batallamos un montón con tu card

2024-05-05 18:00 UTC, merged